# Generated by Django 2.2.10 on 2020-07-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200708_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phome',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
